### ISSUE TITLE
Santizier not disabled on early return

### ISSUE THREAD

**Issue by inkreasing** [realtime-sanitizer/rtsan-standalone-rs#4]
Hi!
when trying out the sanitizer on my porgram it reported violations that seem (from short research) to stem from inside of CoreAudio code. If a violation is found or not can be changed by simple syntactic transformations that don't change the code at all. I managed to reproduce it with small modifications to the cpal beep example, which should be cross-platform.
In the `LiveAudio::test` function i put a alternative version which does exactly the same, but stops reproducing the error. I also tested to check if manually turning off the sanitizer when exiting the function fixes the issue and it does.

From looking at the macro code it seems like early returns aren't protected in any way, so the sanitizer starts sanitizing OS code that called the callback.

Sanitizer Ouput:
```
==37168==ERROR: RealtimeSanitizer: unsafe-library-call
Intercepted call to real-time unsafe function `pthread_mutex_unlock` in real-time context!
    #0 0x00010259a3f4 in pthread_mutex_unlock+0x18 (libclang_rt.rtsan_osx_dynamic.dylib:arm64+0x63f4)
    #1 0x00019751a860 in HALB_Mutex::Unlock()+0x164 (CoreAudio:arm64+0x5b9860)
    #2 0x00019714c984 in HALC_ProxyIOContext::IOWorkLoop()+0x1308 (CoreAudio:arm64+0x1eb984)
    #3 0x00019714aefc in invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int)+0xac (CoreAudio:arm64+0x1e9efc)
    #4 0x0001972f7104 in HALC_IOThread::Entry(void*)+0x54 (CoreAudio:arm64+0x396104)
    #5 0x00019463f2e0 in _pthread_start+0x84 (libsystem_pthread.dylib:arm64+0x72e0)
    #6 0x00019463a0f8 in thread_start+0x4 (libsystem_pthread.dylib:arm64+0x20f8)

SUMMARY: RealtimeSanitizer: unsafe-library-call (CoreAudio:arm64+0x5b9860) in HALB_Mutex::Unlock()+0x164
zsh: abort      cargo run --example beep --features rtsan
```

Reproduction: 
```
use clap::Parser;
use cpal::{
    traits::{DeviceTrait, HostTrait, StreamTrait},
    FromSample, Sample, SizedSample,
};

#[derive(Parser, Debug)]
#[command(version, about = "CPAL beep example", long_about = None)]
struct Opt {
    /// The audio device to use
    #[arg(short, long, default_value_t = String::from("default"))]
    device: String,

    /// Use the JACK host
    #[cfg(all(
        any(
            target_os = "linux",
            target_os = "dragonfly",
            target_os = "freebsd",
            target_os = "netbsd"
        ),
        feature = "jack"
    ))]
    #[arg(short, long)]
    #[allow(dead_code)]
    jack: bool,
}

fn main() -> anyhow::Result<()> {
    let opt = Opt::parse();

    // Conditionally compile with jack if the feature is specified.
    #[cfg(all(
        any(
            target_os = "linux",
            target_os = "dragonfly",
            target_os = "freebsd",
            target_os = "netbsd"
        ),
        feature = "jack"
    ))]
    // Manually check for flags. Can be passed through cargo with -- e.g.
    // cargo run --release --example beep --features jack -- --jack
    let host = if opt.jack {
        cpal::host_from_id(cpal::available_hosts()
            .into_iter()
            .find(|id| *id == cpal::HostId::Jack)
            .expect(
                "make sure --features jack is specified. only works on OSes where jack is available",
            )).expect("jack host unavailable")
    } else {
        cpal::default_host()
    };

    #[cfg(any(
        not(any(
            target_os = "linux",
            target_os = "dragonfly",
            target_os = "freebsd",
            target_os = "netbsd"
        )),
        not(feature = "jack")
    ))]
    let host = cpal::default_host();

    let device = if opt.device == "default" {
        host.default_output_device()
    } else {
        host.output_devices()?
            .find(|x| x.name().map(|y| y == opt.device).unwrap_or(false))
    }
    .expect("failed to find output device");
    println!("Output device: {}", device.name()?);

    let config = device.default_output_config().unwrap();
    println!("Default output config: {:?}", config);

    match config.sample_format() {
        cpal::SampleFormat::I8 => run::<i8>(&device, &config.into()),
        cpal::SampleFormat::I16 => run::<i16>(&device, &config.into()),
        // cpal::SampleFormat::I24 => run::<I24>(&device, &config.into()),
        cpal::SampleFormat::I32 => run::<i32>(&device, &config.into()),
        // cpal::SampleFormat::I48 => run::<I48>(&device, &config.into()),
        cpal::SampleFormat::I64 => run::<i64>(&device, &config.into()),
        cpal::SampleFormat::U8 => run::<u8>(&device, &config.into()),
        cpal::SampleFormat::U16 => run::<u16>(&device, &config.into()),
        // cpal::SampleFormat::U24 => run::<U24>(&device, &config.into()),
        cpal::SampleFormat::U32 => run::<u32>(&device, &config.into()),
        // cpal::SampleFormat::U48 => run::<U48>(&device, &config.into()),
        cpal::SampleFormat::U64 => run::<u64>(&device, &config.into()),
        cpal::SampleFormat::F32 => run::<f32>(&device, &config.into()),
        cpal::SampleFormat::F64 => run::<f64>(&device, &config.into()),
        sample_format => panic!("Unsupported sample format '{sample_format}'"),
    }
}

pub fn run<T>(device: &cpal::Device, config: &cpal::StreamConfig) -> Result<(), anyhow::Error>
where
    T: SizedSample + FromSample<f32> + 'static,
{
    let live_audio = LiveAudio { option: None };

    let err_fn = |err| eprintln!("an error occurred on stream: {}", err);

    let stream = device.build_output_stream(
        config,
        live_audio.get_cb::<T>(),
        err_fn,
        None,
    )?;
    stream.play()?;

    std::thread::sleep(std::time::Duration::from_millis(1000));

    Ok(())
}

struct LiveAudio {
    option: Option<bool>,
}

impl LiveAudio {
    #[rtsan_standalone::nonblocking]
    fn test(&mut self) -> bool {
        // works:
        // self.option.is_none()

        // doesn't work:
        if self.option.is_none() {
            // makes it work again:
            // rtsan_standalone::disable();
            return true;
        }

        false
    }

    fn get_cb<T: Sample + FromSample<f32> + 'static>(mut self) -> impl FnMut(&mut [T], &cpal::OutputCallbackInfo) {
        move |data, info| {
            let _ = self.test();
        }
    }
}

```

**Comment by steckes** [comment]
Hey Luca. 
That is weird, I thought storing the result of the `#block` would work in any case.

Currently it is like this:
```Rust
{
    rtsan_standalone::realtime_enter();
    let __result = #block;
    rtsan_standalone::realtime_exit();
    __result
}
```

Probably it could already help to wrap the #block in another scope.

```Rust
{
    rtsan_standalone::realtime_enter();
    let __result = {
        #block;
    }
    rtsan_standalone::realtime_exit();
    __result
}
```

First I even had it like this, but I removed it because I once had a problem when returning references.

I will write a test for this and see if I find a solution!

**Comment by steckes** [comment]
The curly brackets don't help, but calling it in lambda does!

```Rust
let __result = (|| {
    #block
})();
```

Now I just want to verify that this lambda stays real-time safe depending on the paramaters we pass in and out...

**Comment by steckes** [comment]
Okay I pushed it to the dev branch, you can use that already and test it.
I will just experiment a little bit more with this before releasing it.
Thanks for the report 🙏

**Comment by inkreasing** [comment]
Another solution i thought about was to use a guard struct that disables the sanitizer on drop.

I don't know if there is any meaningful difference between this and using a closure, but it could be worth a try.

**Comment by steckes** [comment]
Yes the guard was my first test as this is how it is intended in C++.
I don't remember what was my initial problem with this, but in my tests now it seems to work fine.

C++ Implementation:
https://github.com/realtime-sanitizer/rtsan/blob/4d5e1e4ffe08db710e5793bbf5ddbe6b2ce08a32/include/rtsan_standalone/rtsan_standalone.h#L60C1-L76C1

**Comment by steckes** [comment]
I pushed a version with guards to the `guards` branch.
Can you test it?

**Comment by inkreasing** [comment]
I get errors that the type needs to be imported. In the scoped_disabler macro you forgot to specify the full path. Looks good otherwise!

**Comment by steckes** [comment]
Good find, and reason to change the tests to have specific imports instead of `::*` :D

It should be fine to give this a `0.1.1` as I guess it should not break any old code.

**Comment by inkreasing** [comment]
Yeah i think so too. I also ran https://github.com/obi1kenobi/cargo-semver-checks (which took really long, i guess it has to run the build script two times) and also no errors there.

Thanks for fixing this so quickly!
